figure(2)
x0=0;
y0=0;
width=10;
height=7;

a = get(gcf,'children');
set(a(2),...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',15,...
'FontName','Times')
ylabel('Magnitude',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',15,...
'FontName','Times')
set(a(3),...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',15,...
'FontName','Times')
ylabel('Phase',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',15,...
'FontName','Times')
xlabel('Frequency',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',15,...
'FontName','Times')
title('')
set(gcf,'units','centimeters ','position',[x0,y0,width,height])
print -deps uncompensated-cs.eps