x = Load.time;
xlab = 'Time(ms)';
y1 = Load.signals(1).values;
y1lab = '$V_{l}$ (V)';
y2 = Load.signals(2).values;
y2lab = '$I_{l}$ (A)';

x0=0;
y0=0;
width=10;
height=7;
set(gcf,'units','centimeters ','position',[x0,y0,width,height])

hAxis(1) = subplot(2,1,1);
plot(x, y1, 'LineWidth',1);
set(gca,...
'Units','normalized',...
'YTick',0:20:80,...
'XTick',0:x(end)/10:x(end),...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',15,...
'FontName','Times')
curtick = get(gca, 'XTick');
set(gca, 'XTickLabel', cellstr(num2str(1000*curtick(:))));
ylabel({y1lab},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',15,...
'FontName','Times')
xlabel(xlab,...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',15,...
'FontName','Times')
ylim([-5 85]);

hAxis(2) = subplot(2,1,2);
hAxis(2).Position(2) = 0.1500;

plot(x, y2, 'LineWidth',1)
set(gca,...
'Units','normalized',...
'YTick',0:2:10,...
'XTick',0:x(end)/10:x(end),...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',15,...
'FontName','Times')
curtick = get(gca, 'XTick');
set(gca, 'XTickLabel', cellstr(num2str(1000*curtick(:))));
ylabel({y2lab},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',15,...
'FontName','Times')
xlabel('Time(ms)',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',15,...
'FontName','Times')
ylim([-1 11]);

print -deps loa_cmc.eps
